name: Bounties
version: 1.0.0
main: org.wasalona.bounties.Bounties
api-version: '1.16'
load: STARTUP
description: Plugin to create bounties on players
author: Ajuuu
website: wasalona.org
commands:
  bounty:
    description: Primary command for bounties
    usage: | 
      /bounty <playername> - Creates a bounty on a player
permissions:
  bounties.*:
    description: Gives access to all bounties commands
    default: op
    children:
      bounties.bounty: true
      bounties.checkcode: true
      bounties.items: true
      bounties.location: true
      bounties.raise: true
      bounties.top: true
  bounties.bounty:
    description: Allows the player the ability to create a bounty
    default: op
  bounties.checkcode:
    description: Allows the player the ability to check the code of a bounty
    default: op
  bounties.items:
    description: Allows the player the ability to check the items of a bounty
    default: op
  bounties.location:
    description: Allows the player the ability to check the location of a target
    default: op
  bounties.raise:
    description: Allows the player the ability to raise a bounty
    default: op
  bounties.top:
    description: Allows the player the ability to check the top bounties
    default: op