name: Bounties
version: '${project.version}'
main: org.wasalona.bounties.Bounties
api-version: '1.16'
load: STARTUP
description: Plugin to create bounties on players
author: Ajuuu
website: wasalona.org
commands:
  bounty:
    description: Create a bounty on a player
    usage: /bounty <playername>
    permission: bounty.create
permissions:
  bounty.create:
    description: Allows the player to run create bounties