name: Bounties
version: '${project.version}'
main: org.wasalona.bounties.Bounties
api-version: '1.16'
load: STARTUP
description: Plugin to create bounties on players
author: Ajuuu
website: wasalona.org
commands:
  bounty:
    description: Primary command for bounties
    usage: | 
      /bounty <playername> - Creates a bounty on a player
      /bounty checkcode <code> - Checks the code of a bounty
      /bounty items <playername> <code> - Gives the reward of a bounty
permissions:
  bounties.*:
    description: Gives access to all bounties commands
    default: op
    children:
      bounties.bounty: true
      bounties.checkcode: true
      bounties.items: true
  bounties.bounty:
    description: Allows the player to create a bounty
    default: op
  bounties.checkcode:
    description: Allows the player to check the code of a bounty
    default: op
  bounties.items:
    description: Allows the player to check the items of a bounty
    default: op